# Create an OSEv3 group that contains the masters and nodes groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=vagrant

# If ansible_ssh_user is not root, ansible_become must be set to true
ansible_become=true

openshift_deployment_type=origin
openshift_release='{{OPENSHIFT_RELEASE}}'

# Specify an exact rpm version to install or configure.
# WARNING: This value will be used for all hosts in RPM based environments, even those that have another version installed.
# This could potentially trigger an upgrade and downtime, so be careful with modifying this value after the cluster is set up.
#openshift_pkg_version=-{{OPENSHIFT_PKG_VERSION}}

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'{{HTPASSWORD_FILENAME}}}]
# Default login account: admin / handhand
openshift_master_htpasswd_users={'admin': '$apr1$gfaL16Jf$c.5LAvg3xNDVQTkk6HpGB1'}

openshift_disable_check=disk_availability,memory_availability,docker_storage,docker_image_availability
openshift_docker_options=" --selinux-enabled --log-driver=journald --storage-driver=overlay --registry-mirror=http://4a0fee72.m.daocloud.io "

# openshift_enable_service_catalog=false
#template_service_broker_install=false

# openshift_hosted_manage_registry=false

# OpenShift Router Options
# Router selector (optional)
# Router will only be created if nodes matching this label are present.
# Default value: 'region=infra'
# openshift_router_selector='node-role.kubernetes.io/infra=true'
# openshift_registry_selector='node-role.kubernetes.io/infra=true'

# default subdomain to use for exposed routes
openshift_master_default_subdomain=apps.cinhtau.io

# logging
openshift_logging_install_logging=false
openshift_logging_es_cluster_size=1
openshift_logging_es_nodeselector={"node-role.kubernetes.io/compute": "true"}
openshift_logging_kibana_nodeselector={"node-role.kubernetes.io/compute": "true"}
openshift_logging_curator_nodeselector={"node-role.kubernetes.io/compute": "true"}
openshift_logging_fluentd_nodeselector={"node-role.kubernetes.io/compute": "true"}
# openshift_logging_storage_kind=dynamic
openshift_logging_es_memory_limit=1G
# openshift_logging_purge_logging=true

# host group for masters
[masters]
master.cinhtau.io openshift_ip={{NETWORK_BASE}}.137 openshift_host={{NETWORK_BASE}}.137 ansible_ssh_private_key_file="/home/vagrant/.ssh/master.key"

# host group for etcd
[etcd]
master.cinhtau.io openshift_ip={{NETWORK_BASE}}.137 openshift_host={{NETWORK_BASE}}.137 ansible_ssh_private_key_file="/home/vagrant/.ssh/master.key"

[nodes]
master.cinhtau.io openshift_ip={{NETWORK_BASE}}.137 openshift_host={{NETWORK_BASE}}.137 ansible_ssh_private_key_file="/home/vagrant/.ssh/master.key" openshift_schedulable=true {{NODE_GROUP_MASTER_INFRA}}
node01.cinhtau.io openshift_ip={{NETWORK_BASE}}.138 openshift_host={{NETWORK_BASE}}.138 ansible_ssh_private_key_file="/home/vagrant/.ssh/node01.key" openshift_schedulable=true {{NODE_GROUP_COMPUTE}}
node02.cinhtau.io openshift_ip={{NETWORK_BASE}}.139 openshift_host={{NETWORK_BASE}}.139 ansible_ssh_private_key_file="/home/vagrant/.ssh/node02.key" openshift_schedulable=true {{NODE_GROUP_COMPUTE}}
